version: "3.7"

services:
  tsbs:
    container_name: tsbs
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm run build
    ports:
      - 3000:80
    networks:
      backend:
      default:
        ipv4_address: 172.20.0.15

networks:
  default:
    external:
      name: proxy
  backend:
    external:
      name: backend