version: "3.7"

services:
  tsbs:
    container_name: tsbs
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm run build
    ports:
      - 3000:80
    networks:
      default:
        ipv4_address: 172.20.0.15

  networks:
    default:
      external:
        name: proxy